name: Blog CI

on:
  push:
    paths:
      - Blog/**
      - Posts/Blog/**
      - .github/**
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@main

    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version: "20.x"

    - name: Enable corepack
      run: corepack enable

    - name: Activate latest Yarn
      run: yarn set version stable

    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan hf.co >> ~/.ssh/known_hosts

    - name: Setup Hexo Dependencies
      run: |
        cp -r Posts/Blog/ Blog/source/_posts
        cd Blog
        yarn

    - name: Setup Git Infomation
      run: |
        git config --global user.name 'Hoshino-Yumetsuki'
        git config --global user.email 'hoshino-yumetsuki@outlook.com'

    - name: Deploy Hexo
      run: |
        cd Blog
        hexo clean
        hexo bangumi -u
        hexo generate
        hexo deploy

    - name: NPM Publish Pre Set
      run: |
        cd Blog
        node ./prescripts/pkgpublish.mjs

    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./Blog/public/package.json
