name: Write CI

on:
  push:
    paths:
      - Write/**
      - Posts/Write/**
      - .github/**
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@main

    - name: Setup Node.js latest
      uses: actions/setup-node@main
      with:
        node-version: "20.x"

    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Setup Hexo Dependencies
      run: |
        cp -r Posts/Write/ Write/source/_posts
        cd Write
        npm i hexo-cli -g
        npm i yarn -g
        yarn

    - name: Setup Git Infomation
      run: |
        git config --global user.name 'Hoshino-Yumetsuki'
        git config --global user.email 'hoshino-yumetsuki@outlook.com'

    - name: Deploy Hexo
      run: |
        cd Write
        hexo clean
        hexo generate
        hexo deploy